services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  ## ResourceTags
  XTags\Infrastructure\Domain\Model\ResourceTags\DoctrineResourceTagsRepository:
    class: XTags\Infrastructure\Domain\Model\ResourceTags\DoctrineResourceTagsRepository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\ResourceRepository'
      $tagRepository: '@XTags\App\Repository\TagRepository'
      $em: '@doctrine.orm.default_entity_manager'

  XTags\Domain\Model\ResourceTags\ResourceTagsRepository:
      alias: XTags\Infrastructure\Domain\Model\ResourceTags\DoctrineResourceTagsRepository

  ## Types
  XTags\Infrastructure\Domain\Model\Types\DoctrineTypesRepository:
    class: XTags\Infrastructure\Domain\Model\Types\DoctrineTypesRepository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\TypeRepository'
      $em: '@doctrine.orm.default_entity_manager'

  XTags\Domain\Model\Types\TypesRepository:
      alias: XTags\Infrastructure\Domain\Model\Types\DoctrineTypesRepository

  ## Tags
  XTags\Infrastructure\Domain\Model\Tags\DoctrineTagsRepository:
    class: XTags\Infrastructure\Domain\Model\Tags\DoctrineTagsRepository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\TagRepository'
      $resourceDomainRepository: '@XTags\Infrastructure\Domain\Model\ResourceTags\DoctrineResourceTagsRepository'
      $tagLabelRepository: '@XTags\Infrastructure\Domain\Model\TagLabel\DoctrineTagLabelRepository'
      $typesRepository: '@XTags\Infrastructure\Domain\Model\Types\DoctrineTypesRepository'
      $vocabularyRepository: '@XTags\Infrastructure\Domain\Model\Vocabularies\DoctrineVocabulariesRespository'
      $em: '@doctrine.orm.default_entity_manager'

  XTags\Domain\Model\Tags\TagsRepository:
      alias: XTags\Infrastructure\Domain\Model\Tags\DoctrineTagsRepository

  ## TagLabel
  XTags\Infrastructure\Domain\Model\TagLabel\DoctrineTagLabelRepository:
    class: XTags\Infrastructure\Domain\Model\TagLabel\DoctrineTagLabelRepository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\LabelRepository'
      $em: '@doctrine.orm.default_entity_manager'

  XTags\Domain\Model\TagLabel\TagLabelRepository:
      alias: XTags\Infrastructure\Domain\Model\TagLabel\DoctrineTagLabelRepository

  ## Vocabularies
  XTags\Infrastructure\Domain\Model\Vocabularies\DoctrineVocabulariesRespository:
    class: XTags\Infrastructure\Domain\Model\Vocabularies\DoctrineVocabulariesRespository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\VocabularyRepository'
      $em: '@doctrine.orm.default_entity_manager'

  XTags\Domain\Model\Vocabularies\VocabulariesRepository:
      alias: XTags\Infrastructure\Domain\Model\Vocabularies\DoctrineVocabulariesRespository

  ## Definition
  XTags\Infrastructure\Domain\Model\Definition\DoctrineDefinitionRepository:
    class: XTags\Infrastructure\Domain\Model\Definition\DoctrineDefinitionRepository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\DefinitionRepository'
      $em: '@doctrine.orm.default_entity_manager'

  XTags\Domain\Model\Definition\DefinitionRepository:
      alias: XTags\Infrastructure\Domain\Model\Definition\DoctrineDefinitionRepository

