services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  ## ResourceTags
  XTags\Infrastructure\Domain\Model\ResourceTags\DoctrineResourceTagsRepository:
    class: XTags\Infrastructure\Domain\Model\ResourceTags\DoctrineResourceTagsRepository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\ResourceRepository'
      $tagRepository: '@XTags\App\Repository\TagRepository'

  XTags\Domain\Model\ResourceTags\ResourceTagsRepository:
      alias: XTags\Infrastructure\Domain\Model\ResourceTags\DoctrineResourceTagsRepository

  ## Types
  XTags\Infrastructure\Domain\Model\Types\DoctrineTypesRepository:
    class: XTags\Infrastructure\Domain\Model\Types\DoctrineTypesRepository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\TypeRepository'

  XTags\Domain\Model\Types\TypesRepository:
      alias: XTags\Infrastructure\Domain\Model\Types\DoctrineTypesRepository

  ## Tags
  XTags\Infrastructure\Domain\Model\Tags\DoctrineTagsRepository:
    class: XTags\Infrastructure\Domain\Model\Tags\DoctrineTagsRepository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\TagRepository'
      $resourceDomainRepository: '@XTags\App\Repository\DoctrineResourceRespository'
      $tagLabelRepository: '@XTags\App\Repository\DoctrineLabelRespository'
      $typesRepository: '@XTags\App\Repository\DoctrinTypeRepository'
      $vocabularyRepository: '@XTags\App\Repository\DoctrineVocabularyRepository'

  XTags\Domain\Model\Tags\TagsRepository:
      alias: XTags\Infrastructure\Domain\Model\Tags\DoctrineTagsRepository

  ## TagLabel
  XTags\Infrastructure\Domain\Model\TagLabel\DoctrineTagLabelRepository:
    class: XTags\Infrastructure\Domain\Model\TagLabel\DoctrineTagLabelRepository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\LabelRepository'

  XTags\Domain\Model\TagLabel\TagLabelRepository:
      alias: XTags\Infrastructure\Domain\Model\TagLabel\DoctrineTagLabelRepository

  ## Vocabularies
  XTags\Infrastructure\Domain\Model\Vocabularies\DoctrineVocabulariesRespository:
    class: XTags\Infrastructure\Domain\Model\Vocabularies\DoctrineVocabulariesRespository
    arguments:
      $doctrineRepository: '@XTags\App\Repository\VocabularyRepository'

  XTags\Domain\Model\Vocabularies\VocabulariesRepository:
      alias: XTags\Infrastructure\Domain\Model\Vocabularies\DoctrineVocabulariesRespository

