
#### VOCABULARIES

###
GET http://localhost/ximdex/xtags/public/index.php/api/vocabularies/search?q=ab

###
GET http://localhost/ximdex/xtags/public/index.php/api/vocabularies/


#### LANGUAGES

###
GET http://localhost/ximdex/xtags/public/index.php/api/languages/


#### TYPES

###
GET http://localhost/ximdex/xtags/public/index.php/api/types


#### TAG_LABEL

###
GET http://localhost/ximdex/xtags/public/index.php/api/tag-label/


#### RESOURCE_TAGS

###
GET http://localhost/ximdex/xtags/public/index.php/api/resource-tags?id=2124bd8e-eabf-4f90-8d2c-2ed1ab121409

###
GET http://localhost/ximdex/xtags/public/index.php/api/resource-tags?id=a4cdcfaf-4ec0-4f0a-ac88-30ae71a2c622&version=1



#### TAGS

###
GET http://localhost/ximdex/xtags/public/index.php/api/tags/