
#### VOCABULARIES

###
GET http://localhost/ximdex/xtags/public/index.php/api/vocabularies/search?q=ab

###
GET http://localhost/ximdex/xtags/public/index.php/api/vocabularies/

### Info detail of definition ID
GET http://localhost/ximdex/xtags/public/index.php/api/vocabularies/info?q=concept6517&vocabulary=1

#### LANGUAGES

###
GET http://localhost/ximdex/xtags/public/index.php/api/languages/


#### TYPES

###
GET http://localhost/ximdex/xtags/public/index.php/api/types


#### TAG_LABEL

###
GET http://localhost/ximdex/xtags/public/index.php/api/tag-label/


#### RESOURCE_TAGS

###
GET http://localhost/ximdex/xtags/public/index.php/api/resource-tags?id=913e923f-3485-41e0-9d0a-cf66f2d8842f

###
GET http://localhost/ximdex/xtags/public/index.php/api/resource-tags?id=a4cdcfaf-4ec0-4f0a-ac88-30ae71a2c622&version=1



#### TAGS

###
GET http://localhost/ximdex/xtags/public/index.php/api/tags/