parameters:

services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  Ximdex\Shared\Infrastructure\Entrypoint\Command\:
    autowire: true
    autoconfigure: true
    resource: '../../../../../Entrypoint/Command/*'
