tags_search.get:
  path: /search
  methods: [GET]
  controller: XTags\Infrastructure\Entrypoint\Controller\TagsController\Search\GetSearchTagsController

tags.default:
  path: /
  methods: [PUT, DELETE, PATCH, GET, POST]
  controller: XTags\Infrastructure\Entrypoint\Controller\NotImplementedController\NotImplementedController

